# Generated by Django 5.0.3 on 2024-03-30 11:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actions',
            new_name='Action',
        ),
        migrations.RenameIndex(
            model_name='action',
            new_name='actions_act_created_64f10d_idx',
            old_name='actions_act_created_639f69_idx',
        ),
        migrations.RenameIndex(
            model_name='action',
            new_name='actions_act_target__f20513_idx',
            old_name='actions_act_target__5ecc2e_idx',
        ),
    ]
